# Use an official Python runtime as a parent image
FROM python:3.9-slim

# Set the working directory
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

RUN apt-get update && apt-get install -y curl && apt-get clean

# Install any needed packages
RUN pip install requests

# Run app.py when the container launches
CMD ["python", "app.py"]
